DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS USER2;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS test_user;
DROP TABLE IF EXISTS video;

CREATE TABLE user(
    id SERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(100)
);
